grammars:
  daffodil:
    type: "classic"
    axiom: "P"
    rules:
      P: "I+[P+O]--//[--L]I[++L]-[PO]++PO"
      I: "FS[//&&L][//^^L]FS"
      S: "SFS"
      L: "[`{+f-ff-f+|+f-ff-f}]"
      O: "[&&&E``/W////W////W////W////W]"
      E: "FF"
      W: "[`^F][{&&&&-f+f|-f+f}]"
    angle: 18
    length: 3
    thickness: 0.5
    n: 5
    camera:
      origin: [-35, 120, 100]
      forward: [0, -1, 0]
      up: [1, 0, 0]
    colors:
      - name: green
        rgb: [0.0, 1.0, 0.0]
      - name: lime
        rgb: [0.3, 1.0, 0.0]
      - name: purple
        rgb: [1.0, 0.0, 1.0]
      - name: yellow
        rgb: [1.0, 1.0, 0.0]
  leaf:
    type: "classic"
    axiom: "[A][B]"
    rules:
      A: "[+A{.].C.}"
      B: "[-B{.].C.}"
      C: "GC"
    angle: 18
    length: 5
    thickness: 1
    n: 10
    colors:
      - name: green
        rgb: [0.0, 1.0, 0.0]

  param_leaf:
    type: "parametric"
    angle: 60
    n: 20
    colors:
      - name: green
        rgb: [0.0, 1.0, 0.0]
    axiom: "{.A(0)}"
    rules:
      A:
        parameters: ['t']
        conds:
          - rvalue: "G(LA,RA)[-B(t).][A(t+1)][+B(t).]"
      B:
        parameters: ['t']
        conds:
          - parameter: 't'
            op: 'gt'
            rvalue: "G(LB,RB)B(t-PD)"
          - parameter: 't'
            op: 'eq'
            rvalue: ""
      G:
        parameters: ['s', 'r']
        conds:
          - rvalue: "G(s*r,r)"
      map:
        LA: 5
        RA: 1.2
        LB: 10.0
        RB: 1
        PD: 0.5

  pointy_leaf:
    type: "parametric"
    angle: 60
    n: 25
    colors:
      - name: green
        rgb: [0.0, 1.0, 0.0]
    axiom: "[{A(0,0).}][{A(0,1).}]"
    rules:
      A:
        parameters: ['t', 'd']
        conds:
          - parameter: 'd'
            op: 'eq'
            rvalue: ".G(LA,RA,-1).[+B(t)G(LC,RC,t).}][+B(t){.]A(t+1,d)"
          - parameter: 'd'
            op: 'eq'
            value: 1
            rvalue: ".G(LA,RA,-1).[-B(t)G(LC,RC,t).}][-B(t){.]A(t+1,d)"
      B:
        parameters: ['t']
        conds:
          - parameter: 't'
            op: 'gt'
            rvalue: "G(LB,RB,-1)B(t-PD)"
          - parameter: 't'
            op: 'eq'
            rvalue: ""
      G:
        parameters: ['s', 'r', 't']
        conds:
          - parameter: 't'
            op: 'gt'
            value: 1
            rvalue: "G(s*r,r,t-1)"
          - parameter: 't'
            op: 'eq'
            value: 1
            rvalue: "G(s,r,0)"
          - parameter: 't'
            op: 'eq'
            rvalue: "G(s,r,0)"
          - parameter: 't'
            op: 'eq'
            value: -1
            rvalue: "G(s*r,r,-1)"
      map:
        LA: 5
        RA: 1.15
        LB: 1.3
        RB: 1.25
        PD: 1
        LC: 3
        RC: 1.19

  hilbert:
    type: "classic"
    axiom: "A"
    rules:
      A: "B-F+CFC+F-D&F^D-F+&&CFC+F+B//`"
      B: "A&F^CFB^F^D^^-F-D^|F^B|FC^F^A//`"
      C: "|D^|F^B-F+C^F^A&&FA&F^C+F+B^F^D//`"
      D: "|CFB-F+B|FA&F^A&&FB-F+B|FC//`"
    angle: 90
    length: 5
    thickness: 1
    n: 3
    colors:
      - name: red
        rgb: [1.0, 0.0, 0.0]
      - name: green
        rgb: [0.0, 1.0, 0.0]
      - name: blue
        rgb: [0.0, 0.0, 1.0]
      - name: yellow
        rgb: [1.0, 1.0, 0.0]

  bush:
    type: "classic"
    axiom: "A"
    rules:
      A: "[&FL[``b]!A]/////[&FL!A]///////[&FL!A]"
      F: "S/////F"
      S: "FL"
      L: "[^^`{-f+f+f-|-f+f+f}]"
    angle: 22.5
    length: 3
    thickness: 0.5
    sph_radius: 0.5
    n: 5
    colors:
      - name: brown
        rgb: [0.08, 0.02, 0.0]
      - name: green
        rgb: [0.0, 0.137, 0.0]
      - name: red
        rgb: [0.8, 0.02, 0.0]

  sphere:
    type: "classic"
    axiom: "A"
    rules:
      A: "bfA"
    angle: 22.5
    length: 3
    thickness: 0.5
    sph_radius: 1
    n: 3
    colors:
      - name: green
        rgb: [0.0, 0.137, 0.0]

#  invalid_grammar_1:
#    axiom: "x"
#    rules:
#      x: "xF"
#
#  invalid_grammar_2:
#    type: "parametric"
#    n: 20
#    axiom: "a(10)"
#    rules:
#      a:
#        parameters: ['t']
#        conds:
#          - op: "gt"
#            rvalue: "a(t-1,5)"

  spiral_tree:
    type: "parametric"
    axiom: "A(10,1)"
    camera:
      origin: [0, 60, 30]
      forward: [0, -1, 0]
      up: [1, 0, 0]
    n: 10
    colors:
      - name: green
        rgb: [0.0, 1.0, 0.0]
    rules:
      A:
        parameters: ['l', 'w']
        conds:
          - rvalue: "!(w)F(l)[&(a1)B(l*r1,w*wr)]/(180)[&(a2)B(l*r2,w*wr)]"
      B:
        parameters: ['l', 'w']
        conds:
          - rvalue: "!(w)F(l)[+(a1)$B(l*r1,w*wr)][-(60)$B(l*r2,w*wr)]"
      map:
        r1: 0.9
        r2: 0.8
        a1: 35
        a2: 35
        wr: 0.707

  christmas_spiral_tree:
    type: "parametric"
    axiom: "A(10,1,11)"
    n: 11
    camera:
      origin: [0, 60, 30]
      forward: [0, -1, 0]
      up: [1, 0, 0]
    rules:
      A:
        parameters: ['l', 'w', 't']
        conds:
          - rvalue: "!(w)F(l)[&(a1)B(l*r1,w*wr,t-1)]/(180)[&(a2)B(l*r2,w*wr,t-1)]"
      B:
        parameters: ['l', 'w', 't']
        conds:
          - parameter: 't'
            op: 'gt'
            rvalue: "!(w)F(l)[+(a1)$B(l*r1,w*wr,t-1)][-(60)$B(l*r2,w*wr,t-1)]"
          - parameter: 't'
            op: 'eq'
            rvalue: "[`b]"
      map:
        r1: 0.9
        r2: 0.7
        a1: 10
        a2: 60
        wr: 0.707
    colors:
      - name: brown
        rgb: [0.38, 0.24, 0.16]
      - name: green
        rgb: [0.0, 1.0, 0.0]

  dead_tree:
    type: "parametric"
    axiom: "A(10, 1)"
    n: 10
    camera:
      origin: [0, 50, 30]
      forward: [0, -1, 0]
      up: [1, 0, 0]
    colors:
      - name: brown
        rgb: [0.38, 0.24, 0.16]
    rules:
      A:
        parameters: ['l', 'w']
        conds:
          - rvalue: "!(w)F(l)[&(a0)B(l*r2,w*wr)]/(d)A(l*r1,w*wr)"
      B:
        parameters: ['l', 'w']
        conds:
          - rvalue: "!(w)F(l)[&(a0)B(l*r2,w*wr)]/(d)A(l*r1,w*wr)"
      C:
        parameters: ['l', 'w']
        conds:
          - rvalue: "!(w)F(l)[+(a2)$B(l*r2,w*wr)]B(l*r1,w*wr)"
      map:
        r1: 0.9
        r2: 0.6
        a0: 45
        a2: 45
        d: 137.5
        wr: 0.707

  weeping_willow:
    type: "parametric"
    axiom: "!(1)F(200)/(45)A"
    n: 6
    colors:
      - name: green
        rgb: [0.0, 1.0, 0.0]
    camera:
      origin: [0, 700, 400]
      forward: [0, -1, 0]
      up: [1, 0, 0]
    tropism:
      T: [-0.02, 0.0, -1.0]
      bend: 0.27
    rules:
      A:
        conds:
          - rvalue: "!(vr)F(50)[&(a)F(50)A]/(d1)[&(a)F(50)A]/(d2)[&(a)F(50)A]"
      B:
        parameters: ['l']
        conds:
          - rvalue: "F(l*lr)"
      "!":
        parameters: ['w']
        conds:
          - rvalue: "!(w*vr)"
      map:
        d1: 112.5
        d2: 157.50
        a: 22.50
        lr: 1.790
        vr: 1.5

  womping_willow:
    type: "parametric"
    axiom: "!(1)F(200)/(45)A"
    n: 6
    colors:
      - name: green
        rgb: [0.0, 1.0, 0.0]
    camera:
      origin: [0, 700, 400]
      forward: [0, -1, 0]
      up: [1, 0, 0]
    tropism:
      T: [-0.61, 0.77, -0.19]
      bend: 0.40
    rules:
      A:
        conds:
          - rvalue: "!(vr)F(50)[&(a)F(50)A]/(d1)[&(a)F(50)A]/(d2)[&(a)F(50)A]"
      B:
        parameters: ['l']
        conds:
          - rvalue: "F(l*lr)"
      "!":
        parameters: ['w']
        conds:
          - rvalue: "!(w*vr)"
      map:
        d1: 180.00
        d2: 252.00
        a: 36.00
        lr: 1.070
        vr: 1.5

  capsella:
    type: "parametric"
    axiom: "I(9)a(13)"
    n: 36
    angle: 18
    camera:
      origin: [0, 300, 150]
      forward: [0, -1, 0]
      up: [1, 0, 0]
    colors:
      - name: green
        rgb: [0.0, 1.0, 0.0]
    rules:
      a:
        parameters: ['t']
        conds:
          - parameter: 't'
            op: 'gt'
            value: 0
            rvalue: "[&(70)L]/(137.5)I(10)a(t-1)"
          - parameter: 't'
            op: 'eq'
            value: 0
            rvalue: "[&(70)L]/(137.5)I(10)A"
      A:
        conds:
          - rvalue: "[&(18)u(4)FFI(10)I(5)X(5)KKKK]/(137.5)I(8)A"
      I:
        parameters: ['t']
        conds:
          - parameter: 't'
            op: 'gt'
            value: 0
            rvalue: "FI(t-1)"
          - parameter: 't'
            op: 'eq'
            value: 0
            rvalue: "F"
      u:
        parameters: ['t']
        conds:
          - parameter: 't'
            op: 'gt'
            value: 0
            rvalue: "FI(t-1)"
          - parameter: 't'
            op: 'eq'
            value: 0
            rvalue: "&(9)"
      L:
        conds:
          - rvalue: "[{.-FI(7)+FI(7)+FI(7)}][{.+FI(7)-FI(7)-FI(7)}]"
      K:
        conds:
          - rvalue: "[&{.+FI(2)--FI(2)}][&{.-FI(2)++FI(2)}]/(90)"
      X:
        parameters: ['t']
        conds:
          - parameter: 't'
            op: 'gt'
            value: 0
            rvalue: "X(t-1)"
          - parameter: 't'
            op: 'eq'
            value: 0
            rvalue: "^(50)[[-GGGG++[GGG[++G{.].].].++GGGG.--GGG.--G.}]%"
